C***  AT     .TRUE. IF AT OBJ
       LOGICAL FUNCTION AT(OBJ)

C  AT(OBJ)      = TRUE IF ON EITHER SIDE OF TWO-PLACED OBJECT

       IMPLICIT INTEGER(A-Z)
       COMMON /LOCCOM/ LOC,OLDLOC,OLDLC2,NEWLOC,MAXLOC
       COMMON /PLACOM/ ATLOC(250),LINK(300),PLACE(150),
     1          FIXED(150),MAXOBJ
       AT=PLACE(OBJ).EQ.LOC.OR.FIXED(OBJ).EQ.LOC
       RETURN
       END
