        SUBROUTINE CIAO
C  EXITS, AFTER ISSUING REMINDER TO SAVE NEW CORE IMAGE.  USED WHEN SUSPENDING
C  AND WHEN CREATING NEW VERSION VIA MAGIC MODE.  ON SOME SYSTEMS, THE CORE
C  IMAGE IS LOST ONCE THE PROGRAM EXITS.  IF SO, SET K=31 INSTEAD OF 32.
        IMPLICIT INTEGER(A-Z)
        DIMENSION VEC(9)
        DATA K/32/,VEC/:74,:70000,:1000,6*0/
        CALL MSPEAK(K)
        CALL SAVE$$(VEC,'ADVE',4,CODE)
        IF(K.EQ.31)CALL GETIN(A,B,C,D)
      CALL BREAK$(.FALSE.)
        CALL EXIT
        END
