C***   CONFUZ


       INTEGER FUNCTION CONFUZ(DUMMY)

C  GENERATES SOME VARIANT OF "DON'T UNDERSTAND THAT" MESSAGE.

       IMPLICIT INTEGER(A-Z)
      LOGICAL PCT
       CONFUZ=60
       IF(PCT(50))CONFUZ=61
       IF(PCT(33))CONFUZ=13
       IF(PCT(25))CONFUZ=347
       IF(PCT(20))CONFUZ=195
       RETURN
       END
