C***   DEAD  .TRUE. IF OBJ IS NOW DEAD
      LOGICAL FUNCTION DEAD(OBJ)
      IMPLICIT INTEGER(A-Z)
      LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
      COMMON/CONCOM/LOCCON(250),OBJCON(150)
      DEAD=BITSET(OBJCON(OBJ),10)
      RETURN
      END
