C***   DROP



       SUBROUTINE DROP(OBJECT,WHERE)

C  PLACE AN OBJECT AT A GIVEN LOC, PREFIXING IT ONTO THE ATLOC LIST.

       IMPLICIT INTEGER(A-Z)
       COMMON /PLACOM/ ATLOC(250),LINK(300),PLACE(150),
     1          FIXED(150),MAXOBJ

       IF(OBJECT.GT.MAXOBJ)GOTO 1
       PLACE(OBJECT)=WHERE
       GOTO 2

1       FIXED(OBJECT-MAXOBJ)=WHERE
2       IF(WHERE.LE.0)RETURN
       LINK(OBJECT)=ATLOC(WHERE)
       ATLOC(WHERE)=OBJECT
       RETURN
       END
