C***   DSTROY


       SUBROUTINE DSTROY(OBJECT)

C  PERMANENTLY ELIMINATE "OBJECT" BY MOVING TO A NON-EXISTENT LOCATION.

       IMPLICIT INTEGER(A-Z)

       CALL MOVE(OBJECT,0)
       RETURN
       END
