C***   EDIBLE  .TRUE. IF OBJ CAN BE EATEN

      LOGICAL FUNCTION EDIBLE(OBJ)
      IMPLICIT INTEGER(A-Z)
      LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
      COMMON/CONCOM/LOCCON(250),OBJCON(150)
      EDIBLE=BITSET(OBJCON(OBJ),7)
      RETURN
      END
