C***  ENCLSD .TURE. IF OBJ INSIDE SOMETHING


       LOGICAL FUNCTION ENCLSD(OBJECT)

C  ENCLSD(OBJ) = TRUE IF THE OBJ IS IN A CONTAINER

       IMPLICIT INTEGER(A-Z)
       COMMON /PLACOM/ ATLOC(250),LINK(300),PLACE(150),
     1          FIXED(150),MAXOBJ
       ENCLSD=PLACE(OBJECT).LT.-1
       RETURN
       END
