       SUBROUTINE GETIN(WORD1,WORD1X,WORD2,WORD2X)

C  GET A COMMAND FROM THE ADVENTURER.  SNARF OUT THE FIRST WORD, PAD IT WITH
C  BLANKS, AND RETURN IT IN WORD1.  CHARS 6 THRU 10 ARE RETURNED IN WORD1X, IN
C  CASE WE NEED TO PRINT OUT THE WHOLE WORD IN AN ERROR MESSAGE.  ANY NUMBER OF
C  BLANKS MAY FOLLOW THE WORD.  IF A SECOND WORD APPEARS, IT IS RETURNED IN
C  WORD2 (CHARS 6 THRU 10 IN WORD2X), ELSE WORD2 IS SET TO ZERO.

       IMPLICIT INTEGER(A-Z)
       LOGICAL BLKLIN
       COMMON /BLKCOM/ BLKLIN
       DIMENSION A(70),TEMP(70)
      REAL*8 WRD(2),WORD1,WORD1X,WORD2,WORD2X

       IF(BLKLIN)PRINT 1
1       FORMAT()
      READ(1,3)A
3       FORMAT(70A1)
      DO 1001 I=1,70
C **************************
C convert lowercase to upper
C **************************
C      IF(A(I).GE.'a'.AND.A(I).LE.'z')A(I)=AND(A(I),:157777)
1001   CONTINUE
      WORD1='     '
      WORD1X='        '
      WORD2=0
10    J=1
      CALL A1TOA5(A,J,WRD,TERM)
      IF(TERM.EQ.'; '.OR.TERM.EQ.0)RETURN
      WORD1=WRD(1)
      WORD1X=WRD(2)
      CALL A1TOA5(A,J,WRD,TERM)
      IF(TERM.EQ.'; '.OR.TERM.EQ.0)RETURN
      WORD2=WRD(1)
      WORD2X=WRD(2)
      RETURN
      END
