C***   HOURS

       SUBROUTINE HOURS

C  ANNOUNCE THE CURRENT HOURS WHEN THE CAVE IS OPEN FOR ADVENTURING.  THIS INFO
C  IS STORED IN WKDAY, WKEND, AND HOLID, WHERE BIT SHIFT(1,N) IS ON IFF THE
C  HOUR FROM N:00 TO N:59 IS "PRIME TIME" (CAVE CLOSED).  WKDAY IS FOR
C  WEEKDAYS, WKEND FOR WEEKENDS, HOLID FOR HOLIDAYS.  NEXT HOLIDAY IS FROM
C  HBEGIN TO HEND.

       IMPLICIT INTEGER(A-Z)
      REAL*8 T1
       DIMENSION HNAME(10),VAL(5)
      INTEGER*4 WKDAY,WKEND,HOLID
      DOUBLE PRECISION MAGIC
       COMMON /WIZCOM/ WKDAY,WKEND,HOLID,HBEGIN,HEND,HNAME,
     1 SHORT,MAGIC,MAGNM,LATNCY,SAVED,SAVET,SETUP
       PRINT 1
1       FORMAT()
       CALL HOURSX(WKDAY,'MON - FRI:')
       CALL HOURSX(WKEND,'SAT - SUN:')
       CALL HOURSX(HOLID,'HOLIDAYS: ')
       CALL DATIME(D,T)
       IF(HEND.LT.D.OR.HEND.LT.HBEGIN)RETURN
       IF(HBEGIN.GT.D)GOTO 10
       PRINT 5,HNAME
5       FORMAT(/' Today is a holiday, namely ',10A2)
       RETURN

10      D=HBEGIN-D
       T1='DAYS,'
       IF(D.EQ.1)T1='DAY, '
       PRINT 15,D,T,HNAME
15     FORMAT(/' The next holiday will be in',I3,' ',A5,' namely ',10A2)
       RETURN
       END
