C***   INSERT

       SUBROUTINE INSERT(OBJECT,CONTNR)

       IMPLICIT INTEGER(A-Z)
       COMMON /HLDCOM/ HOLDER(150),HLINK(150)
       COMMON /LOCCOM/ LOC,OLDLOC,OLDLC2,NEWLOC,MAXLOC
       COMMON /PLACOM/ ATLOC(250),LINK(300),PLACE(150),
     1          FIXED(150),MAXOBJ

       IF(CONTNR.EQ.OBJECT)CALL BUG(32)
       CALL CARRY(OBJECT,LOC)

       TEMP=HOLDER(CONTNR)
       HOLDER(CONTNR)=OBJECT
       HLINK(OBJECT)=TEMP
       PLACE(OBJECT)=-CONTNR
       RETURN

       END
