C***   JUGGLE

       SUBROUTINE JUGGLE(OBJECT)

C  JUGGLE AN OBJECT BY PICKING IT UP AND PUTTING IT DOWN AGAIN, THE PURPOSE
C  BEING TO GET THE OBJECT TO THE FRONT OF THE CHAIN OF THINGS AT ITS LOC.

       IMPLICIT INTEGER(A-Z)
       COMMON /PLACOM/ ATLOC(250),LINK(300),PLACE(150),
     1          FIXED(150),MAXOBJ

       I=PLACE(OBJECT)
       J=FIXED(OBJECT)
       CALL MOVE(OBJECT,I)
       CALL MOVE(OBJECT+MAXOBJ,J)
       RETURN
       END
