C***   LIQ


       INTEGER FUNCTION LIQ(OBJ)
       IMPLICIT INTEGER(A-Z)
       COMMON /LIQCOM/ BOTTLE,CASK,WATER,OIL,WINE,LIQTYP(5)
      INTEGER*4 POINTS
       COMMON /OBJCOM/ PLAC(150),FIXD(150),WEIGHT(150),PROP(150),
     1          POINTS(150)

C       LIQ=LIQ2(MAX0(PROP(OBJ),-1-PROP(OBJ)))
       LIQ=LIQTYP(MAX0(PROP(OBJ)+1,-1-(PROP(OBJ)+1)))
       IF(OBJ.NE.BOTTLE.AND.OBJ.NE.CASK)LIQ=0
       RETURN
       END
