C***   LIQLOC

       INTEGER FUNCTION LIQLOC(LOC)
       IMPLICIT INTEGER(A-Z)
       COMMON /LIQCOM/ BOTTLE,CASK,WATER,OIL,WINE,LIQTYP(5)
      INTEGER*4 LOCCON,OBJCON
      INTEGER*2 WRD(2)
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)
      EQUIVALENCE (LOCCON,WRD)
C      CALL TOOCT(LOCCON(LOC))
C      CALL TOOCT(WRD(LOC*2))

       LIQLOC=LIQ2(INTS(MOD(LOCCON(LOC)/8,2)*(MOD(LOCCON(LOC)/2*2,16)-9)
     1  +1))

       RETURN
       END
