C***  LIVING .TRUE. IF OBJ IS LIVING, BEAR FOR EXAMPLE


       LOGICAL FUNCTION LIVING(OBJ)

C  LIVING(OBJ)  = TRUE IF OBJ IS SOME SORT OF CRITTER

       IMPLICIT INTEGER(A-Z)
       LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)

      LIVING=BITSET(OBJCON(OBJ),9)

       RETURN
       END
