C***   LOOKIN

       SUBROUTINE LOOKIN(CONTNR)

C  LIST CONTENTS IF OBJ IS A CONTAINER AND IS OPEN OR TRANSPARENT.
C  SAVE INITIAL VALUE OF BLKLIN THRU SUBROUTINE.

       IMPLICIT INTEGER(A-Z)
       COMMON /BLKCOM/ BLKLIN
       COMMON /HLDCOM/ HOLDER(150),HLINK(150)
       LOGICAL VESSEL,AJAR,OPAQUE,BLKLIN,BSAVE
       DIMENSION TK(20)

       IF(.NOT.VESSEL(CONTNR).OR.
     1  (.NOT.AJAR(CONTNR).AND.OPAQUE(CONTNR)) )RETURN
       TEMP=HOLDER(CONTNR)
       LOOP=0
       BSAVE=BLKLIN
20      IF(TEMP.EQ.0)RETURN
       BLKLIN=.FALSE.
       IF(LOOP.EQ.0)CALL RSPEAK(360)
      CALL TNOUA('     ',5)
       CALL PSPEAK(TEMP,-1)
       BLKLIN=BSAVE
       TEMP=HLINK(TEMP)
       LOOP=-1
       GOTO 20

       END
