C***   NEWHRX



       INTEGER*4 FUNCTION NEWHRX(DAY)

C  INPUT PRIME TIME SPECS AND SET UP A WORD OF INTERNAL FORMAT.

       IMPLICIT INTEGER(A-Z)
      DIMENSION DDAY(5), DAY(5)

       NEWHRX=0
      DO 8 I=1,5
8     DDAY(I)=DAY(I)
       PRINT 9,DDAY
9       FORMAT(' PRIME TIME ON ',5A2)
10      PRINT 2
2       FORMAT(' FROM:')
      READ(1,3)FROM
3       FORMAT(I4)
       IF(FROM.LT.0.OR.FROM.GE.24)RETURN
       PRINT 4
4       FORMAT(' TILL:')
      READ(1,3)TILL
       TILL=TILL-1
       IF(TILL.LT.FROM.OR.TILL.GE.24)RETURN
       DO 5 I=FROM,TILL
5     NEWHRX=OR(NEWHRX,LS(0000001,I))
       GOTO 10
       END
