C***   NOWAY


       INTEGER FUNCTION NOWAY(DUMMY)

C  GENERATE'S SOME VARIANT OF "CAN'T DO THAT" MESSAGE.

       IMPLICIT INTEGER(A-Z)
      LOGICAL PCT

       NOWAY=14
       IF(PCT(50))NOWAY=110
       IF(PCT(33))NOWAY=147
       IF(PCT(25))NOWAY=250
       IF(PCT(20))NOWAY=262
       IF(PCT(17))NOWAY=25
       IF(PCT(14))NOWAY=345
       IF(PCT(12))NOWAY=346
       RETURN
       END
