C***   OUTSID .TRUE. IF LOCATION IS OUTSIDE THE CAVE


       LOGICAL FUNCTION OUTSID(LOC)

C  OUTSID(LOC)  = TRUE IF LOCATION IS OUTSIDE THE CAVE

       IMPLICIT INTEGER(A-Z)
       LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)

       OUTSID=BITSET(LOCCON(LOC),6)

       RETURN
       END
