C***   POOF

       SUBROUTINE POOF

C  AS PART OF DATABASE INITIALISATION, WE CALL POOF TO SET UP SOME DUMMY
C  PRIME-TIME SPECS, MAGIC WORDS, ETC.

       IMPLICIT INTEGER(A-Z)
       DIMENSION HNAME(10)
      INTEGER*4 WKDAY,WKEND,HOLID
      DOUBLE PRECISION MAGIC
       COMMON /WIZCOM/ WKDAY,WKEND,HOLID,HBEGIN,HEND,HNAME,
     1  SHORT,MAGIC,MAGNM,LATNCY,SAVED,SAVET,SETUP

C       WKDAY="00177000 [CLOSES FROM 9AM - 5PM]
      WKDAY=0
       WKEND=0
       HOLID=0
       HBEGIN=0
       HEND=-1
       SHORT=35
       MAGIC='HOBBIT'
       MAGNM=1
       LATNCY=90
       RETURN
       END
