C***   SMALL  .TRUE. IF IT FITS IN SACK OR SMALL CONTAINER

      LOGICAL FUNCTION SMALL(OBJ)
      IMPLICIT INTEGER(A-Z)
      LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
      COMMON/CONCOM/LOCCON(250),OBJCON(150)
      SMALL=BITSET(OBJCON(OBJ),16)
      RETURN
      END
