C***   VOCAB
C  DATA STRUCTURE ROUTINES
C        (VOCAB, VOCABX, DSTROY, JUGGLE, MOVE, PUT, CARRY, DROP, INSERT, REMOVE)


       INTEGER FUNCTION VOCAB(ID,INIT)

C  THIS DECRYPTS THE WORD BEFORE SENDING IT TO VOCABX, WHO DOES ALL
C  THE REAL WORK.  SEE COMMENTS IN VOCABX.

       IMPLICIT INTEGER(A-Z)
      REAL*8 ID
       VOCAB=VOCABX(ID,INIT)

       RETURN
       END
