C***  WEARNG .TRUE. IF WEARING OBJ


       LOGICAL FUNCTION WEARNG(OBJ)

C  WEARNG(OBJ)  = TRUE IF THE OBJ IS BEING WORN

       IMPLICIT INTEGER(A-Z)
       COMMON /BITCOM/ OPENBT,UNLKBT,BURNBT,WEARBT
      INTEGER*4 LOCCON,OBJCON
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)
      LOGICAL BITSET

       WEARNG=BITSET(OBJCON(OBJ),WEARBT)
       RETURN
       END
