adv660: c/*.c c/*.h
	$(CC) -std=gnu89 -Wno-implicit-function-declaration -Wno-return-type -o adv660 \
                c/advcust.c c/advkern.c c/autop0.c c/autop1.c c/autop2.c c/autop3.c c/autop4.c c/autop5.c

clean:
	rm -f adv660
