       CHARACTER*1 C1ARR
       CHARACTER*5 CARRAY
       LOGICAL KILLED, CLOSED, CLOSNG, LMWARN, PANIC, SCORNG
       COMMON /GENCOM/ PHUCE(2,4),TK(20),KILLED,IWEST,CARRAY(20),
     +   C1ARR(20), ABBNUM, BCROSS, BONUS, ICLK1, CLOCK1, CLOCK2,
     +   CLOCK3, CHASE, CLOSED, CLOSNG, COMBO, DKILL, FOOBAR,
     +   GAVEUP, HEALTH, LMWARN, PANIC, SCORNG, WASTE, DEMO, LIMIT
