        COMMON /PARAMS/ LINSIZ, TRVSIZ, TABSIZ, LOCSIZ, MAXOBJ, VRBSIZ,
     1                  PTBSIZ, ADJSIZ, VKYSIZ, MAXLOC, DWFMAX, RTXSIZ,
     2                  CLSMAX, HNTSIZ, MAGSIZ, MAXMIL, MAXCAR, BUFMAX
