C COPYRIGHT 2001 MYRKRAVERK (MYKRAVERK@USERS.SOURCEFORGE.NET)
C THIS FILE IS DISTRIBUTED UNDER THE GNU GENERAL PUBLIC LICENCE
C SEE THE FILE COPYING FOR DETAILS.

!
      PROGRAM ADVENT
      LOGICAL PROMPT
      CHARACTER*10 CMDLIN
      COMMON /MYRCOM/ PROMPT
      DATA PROMPT/.TRUE./,CMDLIN/'          '/
!      CMDLIN = '          '
      IF(IARGC().GT.0) CALL GETARG(1, CMDLIN)
      IF(CMDLIN.EQ.'-prompt  ') PROMPT = .FALSE.
!      PRINT *,CMDLIN
      CALL AMAIN
! 1    FORMAT('END:')
!      IF(.NOT.PROMPT)WRITE(*,1)
      END
