C***   BITSET
C  MISCELLANEOUS LOGICAL FUNCTIONS (BITSET, PCT)
C  ALSO, SUBROUTINES FOR TURNING BITS ON AND OFF (BITON, BITOFF).

       LOGICAL FUNCTION BITSET(WORD,N)

C  BITSET(COND,L,N) = TRUE IF COND(L) HAS BIT N SET

       IMPLICIT INTEGER(A-Z)
      INTEGER*4 I,WORD

      BITSET=AND(WORD,0000002**N).NE.0
5      RETURN
       END
