C***   BUG

       SUBROUTINE BUG(NUM)
       IMPLICIT INTEGER(A-Z)

C  THE FOLLOWING CONDITIONS ARE CURRENTLY CONSIDERED FATAL BUGS.  NUMBERS < 20
C  ARE DETECTED WHILE READING THE DATABASE; THE OTHERS OCCUR AT "RUN TIME".
C       0       MESSAGE LINE > 70 CHARACTERS
C       1       NULL LINE IN MESSAGE
C       2       TOO MANY WORDS OF MESSAGES
C       3       TOO MANY TRAVEL OPTIONS
C       4       TOO MANY VOCABULARY WORDS
C       5       REQUIRED VOCABULARY WORD NOT FOUND
C       6       TOO MANY RTEXT OR MTEXT MESSAGES
C       7       TOO MANY HINTS
C       8       LOCATION HAS COND BIT BEING SET TWICE
C       9       INVALID SECTION NUMBER IN DATABASE
C       10      OUT OF ORDER LOCS OR RSPEAK ENTRIES.
C       11      ILLEGAL MOTION WORD IN TRAVEL TABLE
C       12      ** UNUSED **.
C       13      UNKNOWN OR ILLEGAL WORD IN ADJECTIVE TABLE.
C       14      ILLEGAL WORD IN PREP/OBJ TABLE
C       15      TOO MANY ENTRIES IN PREP/OBJ TABLE
C       16      OBJECT HAS CONDITION BIT SET TWICE
C       17      OBJECT NUMBER TOO LARGE
C       18      TOO MANY ENTRIES IN ADJECTIVE/NOUN TABLE.
C       20      SPECIAL TRAVEL (500>L>300) EXCEEDS GOTO LIST
C       21      RAN OFF END OF VOCABULARY TABLE
C       22      VERB CLASS (N/1000) NOT BETWEEN 1 AND 3
C       23      INTRANSITIVE ACTION VERB EXCEEDS GOTO LIST
C       24      TRANSITIVE ACTION VERB EXCEEDS GOTO LIST
C       25      CONDITIONAL TRAVEL ENTRY WITH NO ALTERNATIVE
C       26      LOCATION HAS NO TRAVEL ENTRIES
C       27      HINT NUMBER EXCEEDS GOTO LIST
C       28      INVALID MONTH RETURNED BY DATE FUNCTION
C       29      ACTION VERB 'LEAVE' HAS NO OBJECT.
C       30      PREPOSITION FOUND IN UNEXPECTED TABLE
C       31      RECEIVED AN UNEXPECTED WORD TERMINATOR FROM A1TOA5
C       32      TRYING TO PUT A CONTAINER INTO ITSELF (TRICKY!)
C       33      UNKNOWN WORD CLASS IN GETWDS
C       35      TRYING TO CARRY A NON-EXISTENT OBJECT

       PRINT 1, NUM
1       FORMAT (' FATAL ERROR, SEE SOURCE CODE FOR INTERPRETATION.'/
     1  ' PROBABLE CAUSE: ERRONEOUS INFO IN DATABASE.'/
     2  ' ERROR CODE =',I2/)
       STOP
       END
