        SUBROUTINE CIAO
C *WARNING* REMOVED THE FUNCIONALITY OF THIS FUNCTION, I THINK
C MYRKRAVERK
C
C  EXITS, AFTER ISSUING REMINDER TO SAVE NEW CORE IMAGE.  USED WHEN SUSPENDING
C  AND WHEN CREATING NEW VERSION VIA MAGIC MODE.  ON SOME SYSTEMS, THE CORE
C  IMAGE IS LOST ONCE THE PROGRAM EXITS.  IF SO, SET K=31 INSTEAD OF 32.
        IMPLICIT INTEGER(A-Z)
        DIMENSION VEC(9)
C        DATA K/32/,VEC/:74,:70000,:1000,6*0/
        DATA K /31/ !"Break out of this and save your core image"
C        DATA K /32/ !"Be sure to save you core-image..."
        CALL MSPEAK(K)
C        CALL SAVE$$(VEC,'ADVE',4,CODE)
        IF(K.EQ.31)CALL GETIN(A,B,C,D)
C      CALL BREAK$(.FALSE.)
        CALL EXIT
        END
