C***  HERE   .TRUE. IF OBJ AT THIS LOCATION


       LOGICAL FUNCTION HERE(OBJ)

C  HERE(OBJ)    = TRUE IF THE OBJ IS AT "LOC" (OR IS BEING CARRIED)

       IMPLICIT INTEGER(A-Z)
       COMMON /LOCCOM/ LOC,OLDLOC,OLDLC2,NEWLOC,MAXLOC
       COMMON /PLACOM/ ATLOC(250),LINK(300),PLACE(150),
     1          FIXED(150),MAXOBJ
       LOGICAL TOTING
       HERE=PLACE(OBJ).EQ.LOC.OR.TOTING(OBJ)
       RETURN
       END
