C***   LIQ2
C  NON-LOGICAL (ILLOGICAL?) FUNCTIONS (CLASS,LIQ,LIQ2,LIQLOC,VAL)

       INTEGER FUNCTION LIQ2(PBOTL)
       IMPLICIT INTEGER(A-Z)
       COMMON /LIQCOM/ BOTTLE,CASK,WATER,OIL,WINE,LIQTYP(5)

       LIQ2=(1-PBOTL)*WATER+(PBOTL/2)*(WATER+OIL)+(PBOTL/4)
     1  *(WATER+WINE-2*OIL)
       RETURN
       END
