C***   LOCKS  .TRUE. IF YOU CAN LOCK THIS OBJ

      LOGICAL FUNCTION LOCKS(OBJ)
      IMPLICIT INTEGER(A-Z)
      LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
      COMMON/CONCOM/LOCCON(250),OBJCON(150)
      LOCKS=BITSET(OBJCON(OBJ),3)
      RETURN
      END
