C***  OPAQUE .TRUE. IF OBJ IS NON-TRANSPARENT CONTAINER


       LOGICAL FUNCTION OPAQUE(OBJ)

C  OPAQUE(OBJ)  = TRUE IF OBJECT IS NOT TRANSPARENT.  E.G., BAG & CHEST ARE OPAQ
C                 WICKER CAGE & GLASS BOTTLE ARE TRANSPARENT.

       IMPLICIT INTEGER(A-Z)
       LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)

      OPAQUE=BITSET(OBJCON(OBJ),17)

       RETURN
       END
