C***   PORTAL .TRUE. IF LOCATION IS IN CAVE ENTRANCE


       LOGICAL FUNCTION PORTAL(LOC)

C  PORTAL(LOC)  = TRUE IS LOCATION IS IN CAVE "ENTRANCE"

       IMPLICIT INTEGER(A-Z)
       LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)

       PORTAL=BITSET(LOCCON(LOC),5)

       RETURN
       END
