C***  PRINTD .TRUE. IF OBJ CAN BE READ


       LOGICAL FUNCTION PRINTD(OBJ)

C  PRINTD(OBJ)  = TRUE IF OBJECT CAN BE READ.

       IMPLICIT INTEGER(A-Z)
       LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)

      PRINTD=BITSET(OBJCON(OBJ),8)

       RETURN
       END
