C***   PSPEAK



       SUBROUTINE PSPEAK(MSG,SKIP)

C  FIND THE SKIP+1ST MESSAGE FROM MSG AND PRINT IT.  MSG SHOULD BE THE INDEX OF
C  THE INVENTORY MESSAGE FOR OBJECT.  (INVEN+N+1 MESSAGE IS PROP=N MESSAGE).

       IMPLICIT INTEGER(A-Z)
      INTEGER*4 RTEXT,PTEXT,MTEXT,M
C      INTEGER*4 LINES
      CHARACTER*4 LINES
       COMMON /TXTCOM/ LINES(25000),RTEXT(400),PTEXT(150),MTEXT(45)
C MY INDEX HACK (M.V.):
       INTEGER*4 INDEX
       COMMON /COMTXT/ INDEX(25000)
       

       M=PTEXT(MSG)
       IF(SKIP.LT.0)GOTO 9
       DO 3 I=0,SKIP
C1       M=IABS(LINES(M))
 1        M=IABS(INDEX(M)) !HOPE THIS IR RIGHT, NOW (M.V.)
C       IF(LINES(M).GE.0)GOTO 1
          IF(INDEX(M).GE.0) GOTO 1!AND THIS TOO (M.V.)
3       CONTINUE
9       CALL SPEAK(M)
       RETURN
       END
