C***   PUT



       INTEGER FUNCTION PUT(OBJECT,WHERE,PVAL)

C  PUT IS THE SAME AS MOVE, EXCEPT IT RETURNS A VALUE USED TO SET UP THE
C  NEGATED PROP VALUES FOR THE REPOSITORY OBJECTS.

       IMPLICIT INTEGER(A-Z)

       CALL MOVE(OBJECT,WHERE)
       PUT=(-1)-PVAL
       RETURN
       END
