C***   REMOVE


       SUBROUTINE REMOVE(OBJECT)

       IMPLICIT INTEGER(A-Z)
       COMMON /HLDCOM/ HOLDER(150),HLINK(150)
       COMMON /PLACOM/ ATLOC(250),LINK(300),PLACE(150),
     1          FIXED(150),MAXOBJ

       CONTNR=-PLACE(OBJECT)
       PLACE(OBJECT)=-1

       IF(HOLDER(CONTNR).NE.OBJECT)GOTO 1
       HOLDER(CONTNR)=HLINK(OBJECT)
       RETURN

1       TEMP=HOLDER(CONTNR)
2       IF(HLINK(TEMP).EQ.OBJECT)GOTO 3
       TEMP=HLINK(TEMP)
       GOTO 2

3       HLINK(TEMP)=HLINK(OBJECT)
       RETURN
       END
