C***  TREASR .TRUE. IF OBJ IS VALUABLE FOR POINTS


       LOGICAL FUNCTION TREASR(OBJ)

C  TREASR(OBJ)  = TRUE IF OBJECT IS A TREASURE

       IMPLICIT INTEGER(A-Z)
       LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)

       TREASR=BITSET(OBJCON(OBJ),14)

       RETURN
       END
