C***  VESSEL .TRUE. IF OBJ CAN HOLD A LIQUID


       LOGICAL FUNCTION VESSEL(OBJ)

C  VESSEL(OBJ)  = TRUE IF OBJECT IS A CONTAINER

       IMPLICIT INTEGER(A-Z)
       LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
       COMMON /CONCOM/ LOCCON(250),OBJCON(150)

       VESSEL=BITSET(OBJCON(OBJ),15)

       RETURN
       END
