C***   WORN  .TRUE. IF OBJ IS BEING WORN

      LOGICAL FUNCTION WORN(OBJ)
      IMPLICIT INTEGER(A-Z)
      LOGICAL BITSET
      INTEGER*4 LOCCON,OBJCON
      COMMON/CONCOM/LOCCON(250),OBJCON(150)
      WORN=BITSET(OBJCON(OBJ),11)
      RETURN
      END
