C***   YES

       LOGICAL FUNCTION YES(X,Y,Z)

C  CALL YESX (BELOW) WITH MESSAGES FROM SECTION 6.

       IMPLICIT INTEGER(A-Z)
       EXTERNAL RSPEAK
       LOGICAL YESX

       YES=YESX(X,Y,Z,RSPEAK)
       RETURN
       END
